name: Build QMK firmware
on:
  push:
    branches:
      - keychron/q5_pro/iso_encoder
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:  
    build:
      runs-on: ubuntu-latest
      container: ghcr.io/qmk/qmk_cli
      strategy:
        fail-fast: false
        matrix:
          file:
          - crimix.json

      steps:

      - name: Lowercase Github actor name
        run: |
          echo "ACTOR=${GITHUB_ACTOR,,}" >>${GITHUB_ENV}

      - name: Disable git safe directory checks
        run : git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v4
        with:
          repository: Keychron/qmk_firmware
          ref: bluetooth_playground
          submodules: recursive

      - name: Checkout userspace
        uses: actions/checkout@v3
        with:
          path: users/${{ actor }}

      - name: Checkout common userspace
        uses: actions/checkout@v3
        with:
          ref: common
          path: users/${{ actor }}/common

      - name: Build firmware
        run: qmk compile "users/${{ actor }}/${{ matrix.file }}"

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: keychron_q5_pro_iso_encoder
          path: |
            *.hex
            *.bin
            *.uf2
